"""initial schema

Revision ID: 655f3bcb514a
Revises: 
Create Date: 2026-08-12 05:11:25.080230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.types import PortableJSON
from app.core.types import PortableUUID

revision: str = '655f3bcb514a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', PortableUUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('electrical_properties', PortableJSON, nullable=False),
    sa.Column('mechanical_properties', PortableJSON, nullable=False),
    sa.Column('thermal_properties', PortableJSON, nullable=False),
    sa.Column('geometry', PortableJSON, nullable=False),
    sa.Column('simulation_properties', PortableJSON, nullable=False),
    sa.Column('twin_confidence', PortableJSON, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', PortableUUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('motor_sessions',
    sa.Column('id', PortableUUID(), nullable=False),
    sa.Column('owner_id', PortableUUID(), nullable=False),
    sa.Column('asset_id', PortableUUID(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('elapsed_in_state_s', sa.Float(), nullable=False),
    sa.Column('simulated_temp_c', sa.Float(), nullable=False),
    sa.Column('current_a', sa.Float(), nullable=False),
    sa.Column('voltage_v', sa.Float(), nullable=False),
    sa.Column('fault_active', sa.String(length=50), nullable=True),
    sa.Column('motor_parameters', PortableJSON, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motor_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('assets')
    # ### end Alembic commands ###
